import mysql from "mysql2/promise";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import path from "path";
import { existsSync } from "fs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load .env from backend
const envPath = path.join(__dirname, "backend", ".env");
if (existsSync(envPath)) {
  dotenv.config({ path: envPath });
} else {
  dotenv.config();
}

const db = await mysql.createConnection({
  host: process.env.DB_HOST || "localhost",
  user: process.env.DB_USER || "root",
  password: process.env.DB_PASSWORD || "",
  database: process.env.DB_NAME || "gov_scheme_eligibility",
  port: parseInt(process.env.DB_PORT || "3306"),
});

console.log("✅ Connected to database:", process.env.DB_NAME);

// ── Step 1: Remove ALL dummy placeholder schemes ──────────────────────────────
const [del] = await db.execute(`DELETE FROM schemes WHERE scheme_name LIKE 'Verified Welfare Scheme%'`);
console.log(`🗑️  Deleted ${del.affectedRows} dummy placeholder schemes.`);

// ── Step 2: Define real schemes ───────────────────────────────────────────────
const realSchemes = [
  // AGRICULTURE
  {
    scheme_name: "PM Kisan Samman Nidhi", name: "PM Kisan Samman Nidhi",
    department: "Agriculture & Farmers Welfare",
    description: "Direct income support of ₹6,000/year in 3 installments to small and marginal farmers with cultivable land.",
    state: "Central", category: "Agriculture",
    eligibility: "Farmer with cultivable land. Family income under ₹3 lakh/year.",
    benefits: "₹6,000 per year (₹2,000 every 4 months) directly to bank account.",
    documents: "Aadhaar card, bank passbook, land records (Khasra/Khatauni)",
    apply_link: "https://pmkisan.gov.in/", official_link: "https://pmkisan.gov.in/",
    min_age: 18, max_age: null, income_max: 300000, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: 300000,
    age_min: 18, age_max: null, gender: "Any", occupation: "farmer",
    caste_category: null, land_ownership: "required",
    documents_required: "Aadhaar, bank passbook, land records",
  },
  {
    scheme_name: "Pradhan Mantri Fasal Bima Yojana", name: "Pradhan Mantri Fasal Bima Yojana",
    department: "Agriculture",
    description: "Crop insurance scheme providing financial support to farmers suffering crop loss/damage due to natural calamities, pests and diseases.",
    state: "Central", category: "Agriculture",
    eligibility: "All farmers including sharecroppers/tenant farmers growing notified crops.",
    benefits: "Insurance coverage for crop losses; minimal premium (2% for Kharif, 1.5% for Rabi).",
    documents: "Aadhaar, land records, bank passbook, sowing certificate",
    apply_link: "https://pmfby.gov.in/", official_link: "https://pmfby.gov.in/",
    min_age: 18, max_age: null, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: null, gender: "Any", occupation: "farmer",
    caste_category: null, land_ownership: "any",
    documents_required: "Aadhaar, land records, bank passbook",
  },
  {
    scheme_name: "Kisan Credit Card", name: "Kisan Credit Card",
    department: "Agriculture / NABARD",
    description: "Provides farmers with timely credit for agricultural needs, allied activities, and consumption at low interest rates.",
    state: "Central", category: "Agriculture",
    eligibility: "Farmers, fishermen, and self-help groups involved in agriculture or allied activities.",
    benefits: "Short-term credit at 4-7% interest rates; crop insurance coverage.",
    documents: "Aadhaar, land records, bank account details",
    apply_link: "https://www.nabard.org/", official_link: "https://www.nabard.org/",
    min_age: 18, max_age: null, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: null, gender: "Any", occupation: "farmer",
    caste_category: null, land_ownership: "required",
    documents_required: "Aadhaar, land records, bank details",
  },
  {
    scheme_name: "Rythu Bandhu", name: "Rythu Bandhu",
    department: "Telangana Agriculture",
    description: "Investment support to Telangana farmers at ₹5,000 per acre per season for crop investment needs.",
    state: "Telangana", category: "Agriculture",
    eligibility: "All farmers in Telangana who own agricultural land (Pattadar passbook holders).",
    benefits: "₹5,000 per acre per season (Kharif and Rabi) for agricultural inputs.",
    documents: "Pattadar passbook, Aadhaar, bank passbook",
    apply_link: "https://rythubandhu.telangana.gov.in/", official_link: "https://rythubandhu.telangana.gov.in/",
    min_age: 18, max_age: null, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: null, gender: "Any", occupation: "farmer",
    caste_category: null, land_ownership: "required",
    documents_required: "Pattadar passbook, Aadhaar, bank details",
  },
  {
    scheme_name: "Rythu Bima", name: "Rythu Bima",
    department: "Telangana Agriculture",
    description: "Free life insurance scheme for Telangana farmers covering death or permanent disability.",
    state: "Telangana", category: "Agriculture",
    eligibility: "Farmers aged 18-59 with Pattadar passbook in Telangana state.",
    benefits: "₹5 lakh life insurance coverage at zero premium for eligible farmers.",
    documents: "Pattadar passbook, Aadhaar, bank account",
    apply_link: "https://agriculture.telangana.gov.in/", official_link: "https://agriculture.telangana.gov.in/",
    min_age: 18, max_age: 59, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: 59, gender: "Any", occupation: "farmer",
    caste_category: null, land_ownership: "required",
    documents_required: "Pattadar passbook, Aadhaar",
  },
  // EDUCATION & SCHOLARSHIPS
  {
    scheme_name: "National Scholarship Portal", name: "National Scholarship Portal",
    department: "Ministry of Education",
    description: "Central government portal offering scholarships from pre-matric to post-doctoral levels for SC/ST/OBC/Minority/EWS students.",
    state: "Central", category: "Scholarship",
    eligibility: "Students from Class 1 to Ph.D. in SC/ST/OBC/Minority/EWS categories with family income below ₹2.5 lakh.",
    benefits: "Scholarships ranging from ₹1,000 to ₹20,000/year depending on level of study.",
    documents: "Aadhaar, marksheets, income certificate, bank account, caste certificate",
    apply_link: "https://scholarships.gov.in/", official_link: "https://scholarships.gov.in/",
    min_age: 14, max_age: 30, income_max: 250000, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: 250000,
    age_min: 14, age_max: 30, gender: "Any", occupation: "student",
    caste_category: null, land_ownership: "none",
    documents_required: "Marksheets, income certificate, Aadhaar",
  },
  {
    scheme_name: "Post Matric Scholarship SC Students", name: "Post Matric Scholarship SC Students",
    department: "Ministry of Social Justice",
    description: "Financial assistance to Scheduled Caste students studying post-matriculation courses to complete their education.",
    state: "Central", category: "Scholarship",
    eligibility: "SC students pursuing post-matric education with family income below ₹2.5 lakh/year.",
    benefits: "Full maintenance allowance; tuition fees reimbursed; study tour charges covered.",
    documents: "Aadhaar, income certificate, caste certificate, marksheets, bank account",
    apply_link: "https://scholarships.gov.in/", official_link: "https://scholarships.gov.in/",
    min_age: 15, max_age: 30, income_max: 250000, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: 250000,
    age_min: 15, age_max: 30, gender: "Any", occupation: "student",
    caste_category: "SC", land_ownership: "none",
    documents_required: "Caste certificate, income certificate, marksheets",
  },
  {
    scheme_name: "TS ePASS Scholarship", name: "TS ePASS Scholarship",
    department: "Telangana Social Welfare",
    description: "State scholarship for SC/ST/BC/Minority students in Telangana for tuition fee reimbursement and maintenance allowance.",
    state: "Telangana", category: "Scholarship",
    eligibility: "SC/ST/BC/Minority students in Telangana with family income under ₹2 lakh/year.",
    benefits: "Full tuition fee reimbursement; maintenance allowance of ₹700-₹1,200/month.",
    documents: "Aadhaar, caste certificate, income certificate, institution ID, bank account",
    apply_link: "https://telanganaepass.cgg.gov.in/", official_link: "https://telanganaepass.cgg.gov.in/",
    min_age: 14, max_age: 28, income_max: 200000, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: 200000,
    age_min: 14, age_max: 28, gender: "Any", occupation: "student",
    caste_category: "SC", land_ownership: null,
    documents_required: "Caste certificate, income certificate, Aadhaar",
  },
  {
    scheme_name: "Vidya Lakshmi Portal Education Loan", name: "Vidya Lakshmi Portal Education Loan",
    department: "Ministry of Finance & Education",
    description: "Single window portal for students to apply for education loans and government scholarships.",
    state: "Central", category: "Education",
    eligibility: "Students admitted to recognized professional/technical courses.",
    benefits: "Education loans up to ₹7.5 lakh without collateral; up to ₹20 lakh with collateral.",
    documents: "Aadhaar, admission letter, marksheets, income certificate, bank account",
    apply_link: "https://www.vidyalakshmi.co.in/", official_link: "https://www.vidyalakshmi.co.in/",
    min_age: 17, max_age: 35, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 17, age_max: 35, gender: "Any", occupation: "student",
    caste_category: null, land_ownership: "none",
    documents_required: "Admission letter, marksheets, Aadhaar",
  },
  // HOUSING
  {
    scheme_name: "PM Awas Yojana Urban", name: "PM Awas Yojana Urban",
    department: "Ministry of Housing & Urban Affairs",
    description: "Affordable housing for urban poor providing credit-linked subsidy on home loans.",
    state: "Central", category: "Housing",
    eligibility: "Urban households with income up to ₹18 lakh/year who do not own a pucca house.",
    benefits: "Credit Linked Subsidy up to ₹2.67 lakh on home loan interest.",
    documents: "Aadhaar, income proof, residence proof, bank account, no-ownership affidavit",
    apply_link: "https://pmaymis.gov.in/", official_link: "https://pmaymis.gov.in/",
    min_age: 18, max_age: null, income_max: 1800000, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: 1800000,
    age_min: 18, age_max: null, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, income proof, residence proof",
  },
  {
    scheme_name: "PM Awas Yojana Gramin", name: "PM Awas Yojana Gramin",
    department: "Ministry of Rural Development",
    description: "Provides financial assistance for construction of pucca houses with basic amenities for rural BPL families.",
    state: "Central", category: "Housing",
    eligibility: "SECC 2011 listed homeless rural families or those living in kutcha/dilapidated houses.",
    benefits: "₹1.2 lakh (plains) or ₹1.3 lakh (hilly areas) for house construction.",
    documents: "Aadhaar, SECC/BPL card, bank account, land records",
    apply_link: "https://pmayg.nic.in/", official_link: "https://pmayg.nic.in/",
    min_age: 18, max_age: null, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: null, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "required",
    documents_required: "Aadhaar, SECC card, bank account",
  },
  // HEALTH
  {
    scheme_name: "Ayushman Bharat PM-JAY", name: "Ayushman Bharat PM-JAY",
    department: "Ministry of Health & Family Welfare",
    description: "World's largest health insurance scheme providing ₹5 lakh health cover per family per year to poor and vulnerable families.",
    state: "Central", category: "Healthcare",
    eligibility: "Bottom 40% Indian population based on SECC 2011 data.",
    benefits: "₹5 lakh health coverage per family per year for hospitalization.",
    documents: "Aadhaar, ration card/SECC listing, Ayushman card",
    apply_link: "https://pmjay.gov.in/", official_link: "https://pmjay.gov.in/",
    min_age: 0, max_age: null, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 0, age_max: null, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, ration card or SECC inclusion",
  },
  {
    scheme_name: "Aarogyasri Telangana", name: "Aarogyasri Telangana",
    department: "Telangana Health Department",
    description: "State health scheme providing cashless treatment for serious illnesses at network hospitals across Telangana.",
    state: "Telangana", category: "Healthcare",
    eligibility: "All families in Telangana with white/pink ration card or income under ₹5 lakh/year.",
    benefits: "Cashless treatments up to ₹5 lakh per year for 3,000+ medical procedures.",
    documents: "Aadhaar, ration card, income certificate, Aarogyasri card",
    apply_link: "https://aarogyasri.telangana.gov.in/", official_link: "https://aarogyasri.telangana.gov.in/",
    min_age: 0, max_age: null, income_max: 500000, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: 500000,
    age_min: 0, age_max: null, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, ration card",
  },
  {
    scheme_name: "Janani Suraksha Yojana", name: "Janani Suraksha Yojana",
    department: "Ministry of Health",
    description: "Safe motherhood scheme promoting institutional delivery among pregnant women in BPL households.",
    state: "Central", category: "Healthcare",
    eligibility: "Pregnant women from BPL households, especially in low-performing states.",
    benefits: "Cash incentive of ₹700 (rural) to ₹1,400 (urban) per institutional delivery.",
    documents: "Aadhaar, BPL card, MCH card, bank account",
    apply_link: "https://nhm.gov.in/", official_link: "https://nhm.gov.in/",
    min_age: 18, max_age: 45, income_max: null, gender_allowed: "Female",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: 45, gender: "Female", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, BPL card, MCH card",
  },
  // WOMEN WELFARE
  {
    scheme_name: "PM Matru Vandana Yojana", name: "PM Matru Vandana Yojana",
    department: "Ministry of Women & Child Development",
    description: "Maternity benefit providing cash incentives for first live birth to compensate wage loss during pregnancy.",
    state: "Central", category: "Women Welfare",
    eligibility: "Pregnant/lactating mothers aged 19+ for first live birth with family income under ₹8 lakh.",
    benefits: "₹5,000 in 3 installments to compensate for wage loss during pregnancy.",
    documents: "Aadhaar, MCH card, bank account, income certificate",
    apply_link: "https://wcd.nic.in/", official_link: "https://wcd.nic.in/",
    min_age: 19, max_age: null, income_max: 800000, gender_allowed: "Female",
    rules_verified: 1, rule_source: "official-data", income_limit: 800000,
    age_min: 19, age_max: null, gender: "Female", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, MCH card, bank account",
  },
  {
    scheme_name: "Sukanya Samriddhi Yojana", name: "Sukanya Samriddhi Yojana",
    department: "Ministry of Finance",
    description: "Small savings scheme for parents to save for education and marriage expenses of a girl child offering high interest rates.",
    state: "Central", category: "Girls Welfare",
    eligibility: "Parents/guardians of a girl child below 10 years of age.",
    benefits: "High-interest savings account (8.2% p.a.); tax benefits under Section 80C.",
    documents: "Birth certificate of girl child, Aadhaar of parents, bank/post office account",
    apply_link: "https://www.nsiindia.gov.in/", official_link: "https://www.nsiindia.gov.in/",
    min_age: 0, max_age: 10, income_max: null, gender_allowed: "Female",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 0, age_max: 10, gender: "Female", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Birth certificate of girl, Aadhaar of parents",
  },
  {
    scheme_name: "Stree Shakti Loan Scheme", name: "Stree Shakti Loan Scheme",
    department: "SBI / Banking Sector",
    description: "Collateral-free loans to women entrepreneurs for starting or expanding small businesses.",
    state: "Central", category: "Women Entrepreneurship",
    eligibility: "Women owning at least 50% stake in a business, or starting a new enterprise.",
    benefits: "Loans up to ₹5 lakh at concessional interest; 0.5% interest rate concession.",
    documents: "Aadhaar, business plan, bank account, proof of business ownership",
    apply_link: "https://sbi.co.in/", official_link: "https://sbi.co.in/",
    min_age: 18, max_age: 65, income_max: null, gender_allowed: "Female",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: 65, gender: "Female", occupation: "entrepreneur",
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, business plan, ownership proof",
  },
  // ENTREPRENEURSHIP
  {
    scheme_name: "Startup India Seed Fund", name: "Startup India Seed Fund",
    department: "DPIIT",
    description: "Financial assistance to startups for proof of concept, prototype, product trials, market entry and commercialization.",
    state: "Central", category: "Startup",
    eligibility: "DPIIT-recognized startups incorporated not more than 2 years ago.",
    benefits: "₹20 lakh for validation; up to ₹50 lakh for prototype/market entry.",
    documents: "DPIIT registration, business plan, incorporation certificate, bank account",
    apply_link: "https://seedfund.startupindia.gov.in/", official_link: "https://seedfund.startupindia.gov.in/",
    min_age: 21, max_age: 45, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 21, age_max: 45, gender: "Any", occupation: "entrepreneur",
    caste_category: null, land_ownership: "none",
    documents_required: "DPIIT registration, incorporation certificate",
  },
  {
    scheme_name: "MUDRA Loan Shishu", name: "MUDRA Loan Shishu",
    department: "Ministry of MSME",
    description: "Collateral-free micro-credit loans up to ₹50,000 for small businesses and micro-entrepreneurs under PM Mudra Yojana.",
    state: "Central", category: "Entrepreneurship",
    eligibility: "Micro and small enterprises, vendors, traders, and artisans.",
    benefits: "Collateral-free loans up to ₹50,000 at competitive interest rates.",
    documents: "Aadhaar, business proof, bank account, PAN card",
    apply_link: "https://www.mudra.org.in/", official_link: "https://www.mudra.org.in/",
    min_age: 18, max_age: 65, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: 65, gender: "Any", occupation: "self-employed",
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, business proof, PAN card",
  },
  {
    scheme_name: "MUDRA Loan Kishore", name: "MUDRA Loan Kishore",
    department: "Ministry of MSME",
    description: "Loans from ₹50,001 to ₹5 lakh for micro-enterprises that are already established and looking for expansion.",
    state: "Central", category: "Entrepreneurship",
    eligibility: "Established micro and small enterprises needing growth capital.",
    benefits: "Loans from ₹50,001 to ₹5 lakh without collateral requirements.",
    documents: "Aadhaar, business registration, bank statements, PAN card",
    apply_link: "https://www.mudra.org.in/", official_link: "https://www.mudra.org.in/",
    min_age: 18, max_age: 65, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: 65, gender: "Any", occupation: "self-employed",
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, business registration, PAN card",
  },
  {
    scheme_name: "Stand Up India", name: "Stand Up India",
    department: "Ministry of MSME / SIDBI",
    description: "Bank loans between ₹10 lakh to ₹1 crore to SC/ST and women entrepreneurs for greenfield enterprises.",
    state: "Central", category: "Entrepreneurship",
    eligibility: "SC/ST and women entrepreneurs for new greenfield enterprises in manufacturing, services, or trading.",
    benefits: "Loans up to ₹1 crore for greenfield enterprises; repayable in 7 years.",
    documents: "Identity proof, caste certificate (if SC/ST), project report, business plan",
    apply_link: "https://www.standupmitra.in/", official_link: "https://www.standupmitra.in/",
    min_age: 18, max_age: 65, income_max: null, gender_allowed: "Any",
    rules_verified: 0, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: 65, gender: "Any", occupation: "entrepreneur",
    caste_category: "SC", land_ownership: "none",
    documents_required: "Identity proof, caste certificate, project report",
  },
  {
    scheme_name: "PM SVANidhi Street Vendor Loan", name: "PM SVANidhi Street Vendor Loan",
    department: "Ministry of Housing & Urban Affairs",
    description: "Micro-credit scheme for street vendors to resume livelihoods with collateral-free working capital loans.",
    state: "Central", category: "Entrepreneurship",
    eligibility: "Street vendors with identity/recommendation letter from Urban Local Bodies.",
    benefits: "Collateral-free loans of ₹10,000, then ₹20,000, then ₹50,000 progressively.",
    documents: "Aadhaar, vending certificate or ULB recommendation letter, bank account",
    apply_link: "https://pmsvanidhi.mohua.gov.in/", official_link: "https://pmsvanidhi.mohua.gov.in/",
    min_age: 18, max_age: 65, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: 65, gender: "Any", occupation: "self-employed",
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, vending certificate",
  },
  // PENSION & SOCIAL SECURITY
  {
    scheme_name: "PM Shram Yogi Maandhan", name: "PM Shram Yogi Maandhan",
    department: "Ministry of Labour & Employment",
    description: "Pension scheme for unorganized sector workers providing ₹3,000/month pension after age 60.",
    state: "Central", category: "Pension",
    eligibility: "Unorganized workers aged 18-40 with monthly income up to ₹15,000, not covered by EPFO/ESIC.",
    benefits: "₹3,000/month pension after 60; matching government contribution.",
    documents: "Aadhaar, bank account with IFSC, mobile number",
    apply_link: "https://maandhan.in/", official_link: "https://maandhan.in/",
    min_age: 18, max_age: 40, income_max: 180000, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: 180000,
    age_min: 18, age_max: 40, gender: "Any", occupation: "self-employed",
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, bank account",
  },
  {
    scheme_name: "Indira Gandhi National Old Age Pension", name: "Indira Gandhi National Old Age Pension",
    department: "Ministry of Rural Development",
    description: "Monthly pension to the destitute elderly aged 60+ from BPL households under National Social Assistance Programme.",
    state: "Central", category: "Pension",
    eligibility: "Citizens aged 60+ from BPL households.",
    benefits: "₹200/month (age 60-79); ₹500/month (age 80+) from central govt.",
    documents: "Aadhaar, age proof, BPL card, bank account",
    apply_link: "https://nsap.nic.in/", official_link: "https://nsap.nic.in/",
    min_age: 60, max_age: null, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 60, age_max: null, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, age proof, BPL card",
  },
  {
    scheme_name: "Aasara Pension Telangana", name: "Aasara Pension Telangana",
    department: "Telangana Social Welfare",
    description: "Telangana state pension for old age beneficiaries, widows, disabled persons, weavers, and toddy tappers.",
    state: "Telangana", category: "Pension",
    eligibility: "Telangana residents aged 57+ (old age), widows, disabled, and specific occupation groups.",
    benefits: "₹2,016/month pension paid directly to bank account.",
    documents: "Aadhaar, bank account, applicable certificate (disability/widow as relevant)",
    apply_link: "https://aasara.telangana.gov.in/", official_link: "https://aasara.telangana.gov.in/",
    min_age: 57, max_age: null, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 57, age_max: null, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, bank account, eligibility certificate",
  },
  // SKILL DEVELOPMENT / EMPLOYMENT
  {
    scheme_name: "PM Kaushal Vikas Yojana PMKVY", name: "PM Kaushal Vikas Yojana PMKVY",
    department: "Ministry of Skill Development",
    description: "Free short-term skill training and NSQF certification for youth to enhance employability and income.",
    state: "Central", category: "Skill Development",
    eligibility: "Indian youth aged 15-45, especially school/college dropouts and unemployed persons.",
    benefits: "Free training, certification, placement assistance; ₹500/month during training.",
    documents: "Aadhaar, educational certificates, bank account",
    apply_link: "https://www.pmkvyofficial.org/", official_link: "https://www.pmkvyofficial.org/",
    min_age: 15, max_age: 45, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 15, age_max: 45, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, educational certificates",
  },
  {
    scheme_name: "MGNREGS NREGA Rural Employment", name: "MGNREGS NREGA Rural Employment",
    department: "Ministry of Rural Development",
    description: "Guarantees 100 days wage employment per year to rural households whose adult members volunteer for unskilled manual work.",
    state: "Central", category: "Employment",
    eligibility: "Adult members of any rural household willing to do unskilled manual work.",
    benefits: "100 days guaranteed employment at minimum wages; wages paid directly to bank account.",
    documents: "Aadhaar, bank account, job card application at Gram Panchayat",
    apply_link: "https://nrega.nic.in/", official_link: "https://nrega.nic.in/",
    min_age: 18, max_age: null, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: null, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, bank account",
  },
  // SOCIAL WELFARE
  {
    scheme_name: "PM Ujjwala Yojana Free LPG", name: "PM Ujjwala Yojana Free LPG",
    department: "Ministry of Petroleum",
    description: "Provides free LPG connections to women from BPL households to promote clean cooking fuel and improve health.",
    state: "Central", category: "Social Welfare",
    eligibility: "Women from Below Poverty Line (BPL) households with no existing LPG connection.",
    benefits: "Free LPG connection (deposit-free); first refill at subsidized rate.",
    documents: "Aadhaar, BPL/ration card, bank account",
    apply_link: "https://pmuy.gov.in/", official_link: "https://pmuy.gov.in/",
    min_age: 18, max_age: null, income_max: null, gender_allowed: "Female",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: null, gender: "Female", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, BPL/ration card, bank account",
  },
  {
    scheme_name: "National Food Security Act NFSA", name: "National Food Security Act NFSA",
    department: "Ministry of Food & Public Distribution",
    description: "Provides subsidized food grains (rice, wheat, coarse grains) to eligible priority/BPL households.",
    state: "Central", category: "Social Welfare",
    eligibility: "Households covered under NFSA — BPL and priority households identified by states.",
    benefits: "5 kg of food grains per person per month at ₹1-3/kg.",
    documents: "Aadhaar, residence proof, income certificate",
    apply_link: "https://nfsa.gov.in/", official_link: "https://nfsa.gov.in/",
    min_age: 0, max_age: null, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 0, age_max: null, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, residence proof",
  },
  // INSURANCE
  {
    scheme_name: "PM Jeevan Jyoti Bima Yojana", name: "PM Jeevan Jyoti Bima Yojana",
    department: "Ministry of Finance",
    description: "Renewable life insurance offering ₹2 lakh coverage for death due to any cause at just ₹436/year.",
    state: "Central", category: "Insurance",
    eligibility: "Indian citizens aged 18-50 with a savings bank or post office account.",
    benefits: "₹2 lakh life insurance coverage at ₹436/year premium.",
    documents: "Aadhaar, bank account with auto-debit mandate",
    apply_link: "https://financialservices.gov.in/", official_link: "https://financialservices.gov.in/",
    min_age: 18, max_age: 50, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: 50, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, bank account",
  },
  {
    scheme_name: "PM Suraksha Bima Yojana", name: "PM Suraksha Bima Yojana",
    department: "Ministry of Finance",
    description: "Accident insurance offering ₹2 lakh coverage for accidental death or permanent disability at just ₹20/year.",
    state: "Central", category: "Insurance",
    eligibility: "Indian citizens aged 18-70 with savings bank account.",
    benefits: "₹2 lakh for accidental death/total disability; ₹1 lakh for partial disability. Only ₹20/year.",
    documents: "Aadhaar, bank account with auto-debit mandate",
    apply_link: "https://financialservices.gov.in/", official_link: "https://financialservices.gov.in/",
    min_age: 18, max_age: 70, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: 70, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Aadhaar, bank account",
  },
  // DISABILITY
  {
    scheme_name: "ADIP Assistive Devices Disabled", name: "ADIP Assistive Devices Disabled",
    department: "Ministry of Social Justice",
    description: "Provides free aids and assistive devices to persons with disability to help them live independently.",
    state: "Central", category: "Disability Welfare",
    eligibility: "Persons with 40%+ disability; Indian citizen; monthly income under ₹15,000.",
    benefits: "Free devices: wheelchairs, hearing aids, crutches, tricycles, prosthetics.",
    documents: "Disability certificate, Aadhaar, income certificate, bank account",
    apply_link: "https://disabilityaffairs.gov.in/", official_link: "https://disabilityaffairs.gov.in/",
    min_age: 5, max_age: null, income_max: 180000, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: 180000,
    age_min: 5, age_max: null, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "none",
    documents_required: "Disability certificate, Aadhaar, income certificate",
  },
  // SANITATION
  {
    scheme_name: "Swachh Bharat Mission Gramin Toilet", name: "Swachh Bharat Mission Gramin Toilet",
    department: "Ministry of Jal Shakti",
    description: "Incentive for construction of individual household latrines to eliminate open defecation in rural India.",
    state: "Central", category: "Sanitation",
    eligibility: "BPL households and specific APL rural households without a toilet.",
    benefits: "₹12,000 incentive paid after toilet construction and verification.",
    documents: "Aadhaar, bank account, BPL/APL certificate",
    apply_link: "https://sbm.gov.in/", official_link: "https://sbm.gov.in/",
    min_age: 18, max_age: null, income_max: null, gender_allowed: "Any",
    rules_verified: 1, rule_source: "official-data", income_limit: null,
    age_min: 18, age_max: null, gender: "Any", occupation: null,
    caste_category: null, land_ownership: "required",
    documents_required: "Aadhaar, bank account",
  },
];

// ── Step 3: Insert schemes (skip if already exists by scheme_name) ─────────────
const insertSQL = `
INSERT IGNORE INTO schemes (
  scheme_name, name, department, description, state, category,
  eligibility, benefits, documents, apply_link, official_link,
  min_age, max_age, income_max, gender_allowed, rules_verified, rule_source,
  income_limit, age_min, age_max, gender, occupation, caste_category,
  land_ownership, documents_required
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`;

let inserted = 0;
for (const s of realSchemes) {
  try {
    const [result] = await db.execute(insertSQL, [
      s.scheme_name, s.name, s.department, s.description, s.state, s.category,
      s.eligibility, s.benefits, s.documents, s.apply_link, s.official_link,
      s.min_age, s.max_age, s.income_max, s.gender_allowed, s.rules_verified, s.rule_source,
      s.income_limit, s.age_min, s.age_max, s.gender, s.occupation, s.caste_category,
      s.land_ownership, s.documents_required,
    ]);
    if (result.affectedRows > 0) {
      inserted++;
      console.log(`  ✅ Inserted: ${s.scheme_name}`);
    } else {
      console.log(`  ⏭️  Skipped (already exists): ${s.scheme_name}`);
    }
  } catch (err) {
    console.error(`  ❌ Error inserting ${s.scheme_name}:`, err.message);
  }
}

const [[{ total }]] = await db.execute("SELECT COUNT(*) as total FROM schemes");
console.log(`\n🎉 Done! Inserted ${inserted} new schemes. Total schemes in DB: ${total}`);

await db.end();
