-- 11_replace_with_real_schemes.sql
-- Replace temporary scheme rows with real Indian Government schemes

USE gov_scheme_eligibility;

-- Step 1: Remove all temporary "Verified Welfare Scheme" entries
DELETE FROM schemes WHERE scheme_name LIKE 'Verified Welfare Scheme%';

-- Step 2: Insert real Indian Government Schemes (idempotent)

-- AGRICULTURE
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'PM Kisan Samman Nidhi','PM Kisan Samman Nidhi','Agriculture & Farmers Welfare','Direct income support of ₹6,000/year in 3 installments to small and marginal farmers with cultivable land.','Central','Agriculture','Farmer with cultivable land. Family income under ₹3 lakh/year.','₹6,000 per year (₹2,000 every 4 months) directly to bank account.','Aadhaar card, bank passbook, land records (Khasra/Khatauni)','https://pmkisan.gov.in/',18,NULL,300000,'Any',1,'official-data','PM Kisan Samman Nidhi',300000,18,NULL,'Any','farmer',NULL,'required','Aadhaar, bank passbook, land records','https://pmkisan.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'PM Kisan Samman Nidhi');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Pradhan Mantri Fasal Bima Yojana','Pradhan Mantri Fasal Bima Yojana','Agriculture','Crop insurance scheme providing financial support to farmers suffering crop loss or damage due to natural calamities, pests and diseases.','Central','Agriculture','All farmers including sharecroppers/tenant farmers growing notified crops.','Insurance coverage for crop losses; minimal premium (2% for Kharif, 1.5% for Rabi crops).','Aadhaar, land records, bank passbook, sowing certificate','https://pmfby.gov.in/',18,NULL,NULL,'Any',1,'official-data',NULL,18,NULL,'Any','farmer',NULL,'any','Aadhaar, land records, bank passbook','https://pmfby.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Pradhan Mantri Fasal Bima Yojana');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Kisan Credit Card','Kisan Credit Card','Agriculture','Provides farmers with timely and adequate credit for agricultural needs, allied activities, and consumption requirements.','Central','Agriculture','Farmers, fishermen, and self-help groups involved in agriculture or allied activities.','Short-term credit at low interest rates (typically 4-7%); crop insurance coverage.','Aadhaar, land records, bank account details','https://www.nabard.org/content1.aspx?id=572',18,NULL,NULL,'Any',1,'official-data',NULL,18,NULL,'Any','farmer',NULL,'required','Aadhaar, land records, bank details','https://www.nabard.org/content1.aspx?id=572') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Kisan Credit Card');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Rythu Bandhu','Rythu Bandhu','Telangana Agriculture','Investment support to farmers of Telangana state at ₹5,000 per acre per season for crop investment.','Telangana','Agriculture','All farmers in Telangana who own agricultural land.','₹5,000 per acre per season (Kharif and Rabi) for agricultural inputs.','Pattadar passbook, Aadhaar, bank passbook','https://rythubandhu.telangana.gov.in/',18,NULL,NULL,'Any',1,'official-data',NULL,18,NULL,'Any','farmer',NULL,'required','Pattadar passbook, Aadhaar, bank details','https://rythubandhu.telangana.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Rythu Bandhu');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Rythu Bima','Rythu Bima','Telangana Agriculture','Free life insurance scheme for farmers in Telangana covering death or permanent disability.','Telangana','Agriculture','Farmers aged 18-59 who have Pattadar passbook in Telangana.','₹5 lakh life insurance coverage at zero premium for eligible farmers.','Pattadar passbook, Aadhaar, bank account','https://agriculture.telangana.gov.in/',18,59,NULL,'Any',1,'official-data',NULL,18,59,'Any','farmer',NULL,'required','Pattadar passbook, Aadhaar','https://agriculture.telangana.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Rythu Bima');

-- EDUCATION & SCHOLARSHIPS
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'National Scholarship Portal (NSP)','National Scholarship Portal (NSP)','Ministry of Education','Central government portal offering scholarships to students from pre-matric to post-doctoral levels from minorities, SC, ST, OBC, and EWS categories.','Central','Scholarship','Students from Class 1 to Ph.D. from SC/ST/OBC/Minority/EWS categories with family income below ₹2.5 lakh/year.','Scholarships ranging from ₹1,000 to ₹20,000/year depending on level of study.','Aadhaar, marksheets, income certificate, bank account, caste certificate','https://scholarships.gov.in/',14,30,250000,'Any',1,'official-data',250000,14,30,'Any','student',NULL,'none','Marksheets, income certificate, Aadhaar','https://scholarships.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'National Scholarship Portal (NSP)');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Post Matric Scholarship for SC Students','Post Matric Scholarship for SC Students','Social Justice','Financial assistance to Scheduled Caste students studying post-matriculation courses to enable them to complete their education.','Central','Scholarship','SC students pursuing post-matriculation education with family income below ₹2.5 lakh/year.','Full maintenance allowance, study tour charges, thesis typing charges covered.','Aadhaar, income certificate, caste certificate, marksheets, bank account','https://scholarships.gov.in/',15,30,250000,'Any',1,'official-data',250000,15,30,'Any','student','SC','none','Caste certificate, income certificate, marksheets','https://scholarships.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Post Matric Scholarship for SC Students');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Telangana SC/ST Scholarship','Telangana SC/ST Scholarship','Telangana Social Welfare','State scholarship for SC/ST students to support their education costs at government recognized institutions.','Telangana','Scholarship','SC/ST students in Telangana with family income under ₹2 lakh/year.','Tuition fee reimbursement, maintenance allowance of ₹700-₹1,200/month.','Aadhaar, caste certificate, income certificate, institution ID, bank account','https://telanganaepass.cgg.gov.in/',14,28,200000,'Any',1,'official-data',200000,14,28,'Any','student','SC',NULL,'Caste certificate, income certificate, Aadhaar','https://telanganaepass.cgg.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Telangana SC/ST Scholarship');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Vidya Lakshmi Portal','Vidya Lakshmi Portal','Ministry of Finance & Education','Single window portal for students to apply for education loans and government scholarships.','Central','Education','Students admitted to recognized institutions for professional/technical courses.','Education loans of up to ₹7.5 lakh without collateral; up to ₹20 lakh with collateral.','Aadhaar, admission letter, marksheets, income certificate, bank account','https://www.vidyalakshmi.co.in/',17,35,NULL,'Any',1,'official-data',NULL,17,35,'Any','student',NULL,'none','Admission letter, marksheets, Aadhaar','https://www.vidyalakshmi.co.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Vidya Lakshmi Portal');

-- HOUSING
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Pradhan Mantri Awas Yojana (Urban)','Pradhan Mantri Awas Yojana (Urban)','Housing & Urban Affairs','Affordable housing scheme for urban poor providing credit-linked subsidy on home loans.','Central','Housing','Urban households with income up to ₹18 lakh/year who do not own a pucca house.','Credit Linked Subsidy: up to ₹2.67 lakh on home loan interest.','Aadhaar, income proof, residence proof, bank account, no-ownership affidavit','https://pmaymis.gov.in/',18,NULL,1800000,'Any',1,'official-data',1800000,18,NULL,'Any',NULL,NULL,'none','Aadhaar, income proof, residence proof','https://pmaymis.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Pradhan Mantri Awas Yojana (Urban)');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Pradhan Mantri Awas Yojana (Gramin)','Pradhan Mantri Awas Yojana (Gramin)','Rural Development','Provides financial assistance for construction of pucca houses with basic amenities for rural BPL families.','Central','Housing','SECC 2011 listed homeless rural families or those living in kutcha houses.','₹1.2 lakh (plain areas) / ₹1.3 lakh (hilly & difficult areas) for house construction.','Aadhaar, SECC/BPL card, bank account, land records','https://pmayg.nic.in/',18,NULL,NULL,'Any',1,'official-data',NULL,18,NULL,'Any',NULL,NULL,'required','Aadhaar, SECC card, bank account','https://pmayg.nic.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Pradhan Mantri Awas Yojana (Gramin)');

-- HEALTH
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Ayushman Bharat - PM-JAY','Ayushman Bharat - PM-JAY','Health & Family Welfare','World largest health insurance scheme providing ₹5 lakh health cover per family per year to poor and vulnerable families.','Central','Healthcare','Bottom 40% of Indian population based on SECC 2011. No income cap if listed in SECC.','₹5 lakh health coverage per family per year for secondary and tertiary hospitalization.','Aadhaar, ration card/SECC listing, Ayushman card','https://pmjay.gov.in/',0,NULL,NULL,'Any',1,'official-data',NULL,0,NULL,'Any',NULL,NULL,'none','Aadhaar, ration card or SECC inclusion','https://pmjay.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Ayushman Bharat - PM-JAY');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Aarogyasri Health Care Trust','Aarogyasri Health Care Trust','Telangana Health','State health scheme providing cashless treatment for serious illnesses at network hospitals across Telangana.','Telangana','Healthcare','All families in Telangana with white/pink ration card or income under ₹5 lakh/year.','Cashless treatments up to ₹5 lakh per year for 3,000+ medical procedures.','Aadhaar, ration card, income certificate, Aarogyasri card','https://aarogyasri.telangana.gov.in/',0,NULL,500000,'Any',1,'official-data',500000,0,NULL,'Any',NULL,NULL,'none','Aadhaar, ration card','https://aarogyasri.telangana.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Aarogyasri Health Care Trust');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Janani Suraksha Yojana','Janani Suraksha Yojana','Health','Safe motherhood scheme promoting institutional delivery among pregnant women in BPL households.','Central','Healthcare','Pregnant women from BPL households, especially in low-performing states.','Cash incentive of ₹700 (rural) to ₹1,400 (urban) per institutional delivery.','Aadhaar, BPL card, MCH card, bank account','https://nhm.gov.in/',18,45,NULL,'Female',1,'official-data',NULL,18,45,'Female',NULL,NULL,'none','Aadhaar, BPL card, MCH card','https://nhm.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Janani Suraksha Yojana');

-- WOMEN WELFARE
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'PM Matru Vandana Yojana','PM Matru Vandana Yojana','Women & Child Development','Maternity benefit program providing cash incentives for first live birth to compensate wage loss.','Central','Women Welfare','Pregnant and lactating mothers aged 19+ for first live birth, with family income under ₹8 lakh/year.','₹5,000 in 3 installments to compensate for wage loss during pregnancy & child-rearing.','Aadhaar, MCH card, bank account, income certificate','https://wcd.nic.in/',19,NULL,800000,'Female',1,'official-data',800000,19,NULL,'Female',NULL,NULL,'none','Aadhaar, MCH card, bank account','https://wcd.nic.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'PM Matru Vandana Yojana');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Beti Bachao Beti Padhao','Beti Bachao Beti Padhao','Women & Child Development','Scheme to prevent gender-biased sex selective elimination and promote education and welfare of girl child.','Central','Women Welfare','Girl child at birth; families with girl children.','Education support; awareness campaigns; Sukanya Samriddhi Yojana linkages for savings.','Birth certificate, Aadhaar of parents, bank account','https://wcd.nic.in/bbbp-schemes',0,18,NULL,'Female',1,'official-data',NULL,0,18,'Female',NULL,NULL,'none','Birth certificate, Aadhaar of parents','https://wcd.nic.in/bbbp-schemes') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Beti Bachao Beti Padhao');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Stree Shakti Scheme','Stree Shakti Scheme','SBI / Banking','Provides collateral-free loans to women entrepreneurs for starting/expanding businesses.','Central','Women Entrepreneurship','Women owning at least 50% stake in a business or starting a new enterprise.','Loans up to ₹5 lakh at concessional interest rates; interest rate concession of 0.5%.','Aadhaar, business plan, bank account, proof of business ownership','https://sbi.co.in',18,65,NULL,'Female',1,'official-data',NULL,18,65,'Female','entrepreneur',NULL,'none','Aadhaar, business plan, ownership proof','https://sbi.co.in') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Stree Shakti Scheme');

-- ENTREPRENEURSHIP / MSME
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Startup India Seed Fund','Startup India Seed Fund','DPIIT','Provides financial assistance to startups for proof of concept, prototype development, product trials, market entry, and commercialization.','Central','Startup','DPIIT-recognized startups incorporated not more than 2 years ago.','₹20 lakh for validation; up to ₹50 lakh for prototype/market entry.','DPIIT registration, business plan, incorporation certificate, bank account','https://www.startupindia.gov.in/content/sif/en/startup-scheme.html',21,45,NULL,'Any',1,'official-data',NULL,21,45,'Any','entrepreneur',NULL,'none','DPIIT registration, incorporation certificate','https://seedfund.startupindia.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Startup India Seed Fund');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'PM SVANidhi','PM SVANidhi','Housing & Urban Affairs','Micro-credit scheme for street vendors to help them resume livelihoods after COVID-19 disruptions.','Central','Entrepreneurship','Street vendors with identity/letter of recommendation from Urban Local Bodies.','Collateral-free working capital loans of ₹10,000, ₹20,000 and ₹50,000.','Aadhaar, vending certificate or letter of recommendation, bank account','https://svamitva.nic.in/',18,65,NULL,'Any',1,'official-data',NULL,18,65,'Any','self-employed',NULL,'none','Aadhaar, vending certificate','https://pmsvanidhi.mohua.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'PM SVANidhi');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Stand Up India','Stand Up India','MSME / Sidbi','Facilitates bank loans between ₹10 lakh to ₹1 crore to at least one SC or ST borrower and at least one woman borrower per bank branch for greenfield enterprises.','Central','Entrepreneurship','SC/ST and women entrepreneurs for new enterprises in manufacturing, services, or trading.','Loans up to ₹1 crore for greenfield enterprises; repayable in 7 years.','Identity proof, caste certificate (if SC/ST), project report, business plan','https://www.standupmitra.in/',18,65,NULL,'Any',0,'official-data',NULL,18,65,'Any','entrepreneur','SC','none','Identity proof, caste certificate, project report','https://www.standupmitra.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Stand Up India');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'MUDRA Yojana (Shishu)','MUDRA Yojana (Shishu)','MSME','Provides collateral-free loans up to ₹50,000 for small businesses and micro-entrepreneurs under Pradhan Mantri Mudra Yojana.','Central','Entrepreneurship','Micro and small enterprises, vendors, traders, and artisans.','Collateral-free loans up to ₹50,000 at competitive interest rates.','Aadhaar, business proof, bank account, PAN card','https://www.mudra.org.in/',18,65,NULL,'Any',1,'official-data',NULL,18,65,'Any','self-employed',NULL,'none','Aadhaar, business proof, PAN card','https://www.mudra.org.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'MUDRA Yojana (Shishu)');

-- PENSION & SOCIAL SECURITY
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'PM Shram Yogi Maandhan Yojana','PM Shram Yogi Maandhan Yojana','Labour & Employment','Pension scheme for unorganized sector workers providing them assured monthly pension of ₹3,000 after age 60.','Central','Pension','Unorganized workers aged 18-40 with monthly income up to ₹15,000 and not covered under EPFO/ESIC/NPS.','Monthly pension of ₹3,000 after age 60; matching contribution made by government.','Aadhaar, bank account with IFSC, mobile number','https://maandhan.in/',18,40,180000,'Any',1,'official-data',180000,18,40,'Any','self-employed',NULL,'none','Aadhaar, bank account','https://maandhan.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'PM Shram Yogi Maandhan Yojana');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Indira Gandhi National Old Age Pension','Indira Gandhi National Old Age Pension','Rural Development','Provides monthly pension to the destitute elderly aged 60 years and above from BPL households.','Central','Pension','Citizens aged 60+ from BPL households.','₹200/month for 60-79 years; ₹500/month for 80+ years (Central share).','Aadhaar, age proof, BPL card, bank account','https://nsap.nic.in/',60,NULL,NULL,'Any',1,'official-data',NULL,60,NULL,'Any',NULL,NULL,'none','Aadhaar, age proof, BPL card','https://nsap.nic.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Indira Gandhi National Old Age Pension');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Aasara Pension','Aasara Pension','Telangana Social Welfare','Telangana state pension scheme for old age, widows, disabled persons, weavers, and toddy tappers.','Telangana','Pension','Residents of Telangana aged 57+ (old age), widows, disabled persons, and specific occupation groups.','₹2,016/month pension for eligible beneficiaries.','Aadhaar, bank account, caste/disability/widow certificate as applicable','https://aasara.telangana.gov.in/',57,NULL,NULL,'Any',1,'official-data',NULL,57,NULL,'Any',NULL,NULL,'none','Aadhaar, bank account, eligibility certificate','https://aasara.telangana.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Aasara Pension');

-- SKILL DEVELOPMENT / EMPLOYMENT
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)','Pradhan Mantri Kaushal Vikas Yojana (PMKVY)','Skill Development','Free short-term skill training and certification for youth to enhance employability and income.','Central','Skill Development','Indian youth, especially school/college dropouts or unemployed aged 15-45.','Free training, certification, and placement assistance; monetary reward of ₹500 per month during training.','Aadhaar, educational certificates, bank account','https://www.pmkvyofficial.org/',15,45,NULL,'Any',1,'official-data',NULL,15,45,'Any',NULL,NULL,'none','Aadhaar, educational certificates','https://www.pmkvyofficial.org/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'MGNREGS (NREGA)','MGNREGS (NREGA)','Rural Development','Guarantees 100 days of wage employment per year to every rural household whose adult members volunteer to do unskilled manual work.','Central','Employment','Adult members of any rural household willing to do unskilled manual work.','100 days of guaranteed employment at minimum wage rates; wages paid directly to bank account.','Aadhaar, bank account, job card application','https://nrega.nic.in/',18,NULL,NULL,'Any',1,'official-data',NULL,18,NULL,'Any',NULL,NULL,'none','Aadhaar, bank account','https://nrega.nic.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'MGNREGS (NREGA)');

-- SOCIAL WELFARE / BPL
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'PM Ujjwala Yojana','PM Ujjwala Yojana','Petroleum & Natural Gas','Provides free LPG connections to women from BPL households to promote clean cooking fuel.','Central','Social Welfare','Women from Below Poverty Line (BPL) households with no existing LPG connection in their name.','Free LPG connection (deposit-free); first refill at subsidized rate.','Aadhaar, BPL/ration card, bank account','https://pmuy.gov.in/',18,NULL,NULL,'Female',1,'official-data',NULL,18,NULL,'Female',NULL,NULL,'none','Aadhaar, BPL/ration card, bank account','https://pmuy.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'PM Ujjwala Yojana');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'National Food Security Act (Ration Card)','National Food Security Act (Ration Card)','Food & Public Distribution','Provides subsidized food grains (rice, wheat, coarse grains) to eligible BPL and priority households.','Central','Social Welfare','Households covered under NFSA - BPL families or those identified by state governments.','5 kg of food grains per person per month at ₹1-3/kg.','Aadhaar, residence proof, income certificate','https://nfsa.gov.in/',0,NULL,NULL,'Any',1,'official-data',NULL,0,NULL,'Any',NULL,NULL,'none','Aadhaar, residence proof','https://nfsa.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'National Food Security Act (Ration Card)');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Sukanya Samriddhi Yojana','Sukanya Samriddhi Yojana','Finance','Small savings scheme for parents/guardians to save for education and marriage expenses of a girl child.','Central','Girls Welfare','Parents/guardians of a girl child below 10 years of age.','High-interest savings account (currently 8.2% p.a.); tax benefits under Section 80C.','Birth certificate of girl child, Aadhaar of parents, bank/post office account','https://www.nsiindia.gov.in/',0,10,NULL,'Female',1,'official-data',NULL,0,10,'Female',NULL,NULL,'none','Birth certificate of girl, Aadhaar of parents','https://www.nsiindia.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Sukanya Samriddhi Yojana');

-- DISABILITY
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'ADIP Scheme (Assistance to Disabled)','ADIP Scheme (Assistance to Disabled)','Social Justice','Provides aids and assistive devices to persons with disability to help them live independently and productively.','Central','Disability Welfare','Persons with 40%+ disability; Indian citizen; monthly income under ₹15,000.','Free assistive devices like wheelchairs, hearing aids, crutches, tricycles, prosthetics.','Disability certificate, Aadhaar, income certificate, bank account','https://disabilityaffairs.gov.in/',5,NULL,180000,'Any',1,'official-data',180000,5,NULL,'Any',NULL,NULL,'none','Disability certificate, Aadhaar, income certificate','https://disabilityaffairs.gov.in/') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'ADIP Scheme (Assistance to Disabled)');

-- SANITATION
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Swachh Bharat Mission (Gramin)','Swachh Bharat Mission (Gramin)','Jal Shakti / Rural Development','Provides incentive for construction of individual household toilets to eliminate open defecation in rural India.','Central','Sanitation','BPL households and specific APL households in rural areas without a toilet.','₹12,000 incentive for construction of household toilet (paid after verification).','Aadhaar, bank account, BPL/APL certificate','https://swachhbharat.mygov.in/',18,NULL,NULL,'Any',1,'official-data',NULL,18,NULL,'Any',NULL,NULL,'required','Aadhaar, bank account','https://sbm.gov.in/sbmReport/home.aspx') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Swachh Bharat Mission (Gramin)');

-- INSURANCE
INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Pradhan Mantri Jeevan Jyoti Bima Yojana','Pradhan Mantri Jeevan Jyoti Bima Yojana','Finance / Insurance','Renewable life insurance scheme offering coverage of ₹2 lakh for death due to any cause.','Central','Insurance','Indian citizens aged 18-50 with a savings bank/post office account.','₹2 lakh life insurance coverage at just ₹436/year premium.','Aadhaar, bank account with auto-debit mandate','https://financialservices.gov.in/',18,50,NULL,'Any',1,'official-data',NULL,18,50,'Any',NULL,NULL,'none','Aadhaar, bank account','https://financialservices.gov.in/insurance-divisions/Government-Sponsored-Socially-Oriented-Insurance-Schemes/Pradhan-Mantri-Jeevan-Jyoti-Bima-Yojana(PMJJBY)') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Pradhan Mantri Jeevan Jyoti Bima Yojana');

INSERT INTO schemes (scheme_name, name, department, description, state, category, eligibility, benefits, documents, apply_link, min_age, max_age, income_max, gender_allowed, rules_verified, rule_source, income_limit, age_min, age_max, gender, occupation, caste_category, land_ownership, documents_required, official_link)
SELECT * FROM (SELECT 'Pradhan Mantri Suraksha Bima Yojana','Pradhan Mantri Suraksha Bima Yojana','Finance / Insurance','Accident insurance scheme offering coverage for accidental death or disability at a very low premium.','Central','Insurance','Indian citizens aged 18-70 with savings bank account.','₹2 lakh for accidental death/total disability; ₹1 lakh for partial disability. Premium: ₹20/year.','Aadhaar, bank account with auto-debit mandate','https://financialservices.gov.in/',18,70,NULL,'Any',1,'official-data',NULL,18,70,'Any',NULL,NULL,'none','Aadhaar, bank account','https://financialservices.gov.in/insurance-divisions/Government-Sponsored-Socially-Oriented-Insurance-Schemes/Pradhan-Mantri-Suraksha-Bima-Yojana(PMSBY)') AS tmp
WHERE NOT EXISTS (SELECT 1 FROM schemes WHERE scheme_name = 'Pradhan Mantri Suraksha Bima Yojana');
